### ISSUE TITLE
ctrl+[ and ctrl+shift+{ no longer insert template tags and variables in django html templates

### ISSUE THREAD

**Issue by derek73** [textmate/python-django.tmbundle#2]
Prior to the recent updates to this bundle, when editing a "HTML (Django)" file you could insert template variables and tags using `ctrl + [` and `ctrl + shift + {`. These no longer function. 

`ctrl + [`

would insert 

`{{ | }}`

and  `ctrl + shift + {` would insert

`{% | %}`

(where pipe/| is the cursor)

If there's another way to do the same thing that I'm missing, let me know. They were very handy and I used them all the time so would be nice to still have some way to do that. (I may have them reversed. I'd be happy with however they used to be or however makes sense to you. I know I can set them up myself in a custom bundle and will probably do so after it becomes annoying enough to motivate me to do more than submit an issue on GitHub.)

I'm using TextMate version 2.0-alpha.9561

**Comment by infininight** [comment]
I changed the shortcuts around a bit when I did the updates. The shortcuts are now:

`⌃>` – Block Tag
`⌃{` – Variable Tag
`⌃#` – Comment Tag

(Since all require shift since they are required to enter the second key.)

In addition you can now use `⌃>` to cycle between the two main tag types when inside a tag. This was done to be more in line other bundles to move to a standard 'insert template tag' shortcut. It also mirrors the HTML `⌃<` shortcut nicely.

You can of course change the shortcut if you like the old one in the bundle editor. Just click in the shortcut field and choose whichever shortcut you like.

**Comment by derek73** [comment]
Thanks for the note. That sounds great. The toggle works for me when I put my cursor in an existing tag (very cool!). But I can't get the other ones to work.

Attaching a screenshot of my edit bundles interface. I see menu action items like `templatetag: closevariable`. They have no key equivalent, and they seem to output things like `{% templatetag closevariable %}` on a tab trigger to `}}`. I'm not sure if that's the intended functionality and maybe I just don't understand how to use it, or maybe something is not as you expected. 

![screen shot 2014-09-03 at 9 57 44 pm](https://cloud.githubusercontent.com/assets/18306/4145090/a224780c-33f0-11e4-83bb-b1a9ffe4a55b.png)

**Comment by infininight** [comment]
You are missing some bundle items there which means you have some version conflicts. Try reverting your bundles:

https://github.com/textmate/textmate/wiki/Reverting-To-Defaults

Start by checking `~/Library/Application Support/Avian/Bundles` for a Django bundle or a Django Templates bundle and removing those before going through the entire process on that page.

**Comment by derek73** [comment]
Thanks for the tip. That worked or me.
